### ISSUE TITLE
Add platform to compose

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/docker-training#158]
```
version: '3.9'
name: example
services:
  foo:
    build: ./foo
    image: reg.istry.cz/ondrej/foo
    platform: linux/amd64
```
