### ISSUE TITLE
docker compose inline dockerfile

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/docker-training#162]
```yaml
version: '3.8'
services:
  example:
    build:
      dockerfile_inline: |
        FROM debian:12-slim
        CMD ["echo", "Hello from inline Dockerfile"]
```
