### ISSUE TITLE
Add example: docker compose - run multiple instances on different ports

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/docker-training#163]
```yaml
version: '3.8'
services:
  example0: &example
    image: sikalabs/hello-world-server
    environment:
      TEXT: Hello Docker Training!
    ports:
      - 8000:8000
  example1:
    <<: *example
    ports:
      - 8001:8000
  example2:
    <<: *example
    ports:
      - 8002:8000
```
