### ISSUE TITLE
docker compose healthcheck

### ISSUE THREAD

**Issue by ondrejsika** [ondrejsika/docker-training#179]
```
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 2m
```
